apiVersion: v2
name: peche-fiches-normandie
description: Chart Helm pour l'application Fiches Techniques Pêche Normandie
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - peche
  - normandie
  - kubernetes
  - web
maintainers:
  - name: Pêche Normandie
